### ISSUE TITLE
Refactor KenKenPaProcessor

### ISSUE THREAD

**Issue by shiraji** [shiraji/kenkenpa#14]
KenKenPaProcessor seems too big to implement new feature.

Let's create model that handle each java class's annotations.

**Comment by shiraji** [comment]
Let me tidy this issue.

## Problem
- Need model for handling annotations
- [Member variables](https://github.com/shiraji/kenkenpa/blob/v1.0.3/kenkenpa-compiler/src/main/java/com/github/shiraji/kenkenpa/compiler/KenKenPaProcessor.java#L75-L79) should go to the model
- May need to have model for each annotation
- However, state should be keep in one place
- Member variable use map but in same case, it doesn't use it. Rethink how to store data.

## TODO
- [ ] Move to Kotlin
- [ ] create model for state
- [ ] create model for `@Hop`/`@Hops`
- [ ] create model for `@TakeOff`
- [ ] create model for `@Land`

**Comment by shiraji** [comment]
I'm start thinking it is time to move to Kotlin.
